"""
create_production_db.py
=======================
Creates a realistic production database simulating a real open-source
e-commerce / SaaS project. Real table names, real-looking data.
This is NOT generated by demo_cli, it's a standalone real project database.

Run: python create_production_db.py
"""
import sqlite3, os

DB = "production.db"

if os.path.exists(DB):
    os.remove(DB)

con = sqlite3.connect(DB)

con.executescript("""
CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    password_hash TEXT,
    role TEXT DEFAULT 'user',
    created_at TEXT,
    last_login TEXT,
    is_active INTEGER DEFAULT 1
);

CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price REAL NOT NULL,
    stock INTEGER DEFAULT 0,
    category TEXT,
    created_at TEXT,
    is_example INTEGER DEFAULT 0
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    total REAL NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TEXT,
    shipped_at TEXT,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
    id INTEGER PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price REAL NOT NULL,
    FOREIGN KEY(order_id) REFERENCES orders(id),
    FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE migrations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL
);
""")

con.executemany("INSERT INTO users VALUES (?,?,?,?,?,?,?,?)", [
    (1,  "admin",       "admin@example.com",       "hash_x9k2", "admin", "2022-03-15", "2026-06-14", 1),
    (2,  "alice",       "alice@example.com",       "hash_a1b2", "user",  "2022-05-20", "2026-06-10", 1),
    (3,  "bob",         "bob@example.com",         "hash_b3c4", "user",  "2022-08-11", "2026-05-28", 1),
    (4,  "carol",       "carol@example.com",     "hash_c5d6", "user",  "2023-01-04", "2026-06-01", 1),
    (5,  "dave",        "dave@example.com",        "hash_d7e8", "user",  "2023-03-22", "2026-04-15", 1),
    (6,  "eve",         "eve@example.com",          "hash_e9f0", "staff", "2023-06-30", "2026-06-13", 1),
    (7,  "frank",       "frank@example.com",       "hash_f1g2", "user",  "2023-09-14", "2026-03-20", 1),
    (8,  "grace",       "grace@example.com",     "hash_g3h4", "user",  "2024-01-08", "2026-06-12", 1),
    (9,  "henry",       "henry@example.com",       "hash_h5i6", "user",  "2024-04-17", "2026-05-30", 1),
    (10, "iris",        "iris@example.com",       "hash_i7j8", "user",  "2024-07-23", "2026-06-14", 1),
    (11, "old_user_1",  "old1@example.com",      "hash_old1", "user",  "2009-11-01", "2010-02-14", 0),
    (12, "old_user_2",  "old2@example.com",      "hash_old2", "user",  "2008-06-15", "2009-08-20", 0),
])

con.executemany("INSERT INTO products VALUES (?,?,?,?,?,?,?,?)", [
    (1, "Laptop Pro 15",      "High-performance laptop",      1299.99, 45, "electronics", "2023-01-10", 0),
    (2, "Wireless Mouse",     "Ergonomic wireless mouse",       29.99, 230,"accessories", "2023-02-14", 0),
    (3, "USB-C Hub 7-in-1",   "Multi-port USB-C hub",           49.99, 180,"accessories", "2023-03-20", 0),
    (4, "4K Monitor 27inch",  "Ultra-wide 4K display",         449.99, 32, "electronics", "2023-04-05", 0),
    (5, "Mechanical Keyboard","RGB mechanical keyboard",        89.99, 95, "accessories", "2023-05-18", 0),
    (6, "Webcam HD 1080p",    "HD webcam with mic",             59.99, 140,"accessories", "2023-06-22", 0),
    (7, "SSD 1TB External",   "Portable SSD drive",             99.99, 88, "storage",     "2023-08-30", 0),
    (8, "Noise Cancel Headph","Premium noise-cancelling",      199.99, 62, "audio",       "2023-10-12", 0),
    (9, "Old Product A",      "Discontinued item",               9.99,  0, "misc",        "2009-05-01", 1),
    (10,"Old Product B",      "Discontinued item",              14.99,  0, "misc",        "2008-12-01", 1),
])

con.executemany("INSERT INTO orders VALUES (?,?,?,?,?,?)", [
    (1, 2, 1329.98, "delivered",  "2024-01-15", "2024-01-18"),
    (2, 3,   49.99, "delivered",  "2024-02-20", "2024-02-23"),
    (3, 4,  539.98, "delivered",  "2024-03-10", "2024-03-13"),
    (4, 5,   89.99, "delivered",  "2024-05-05", "2024-05-08"),
    (5, 6,  259.98, "delivered",  "2024-07-22", "2024-07-25"),
    (6, 7,   99.99, "shipped",    "2024-09-14", "2024-09-17"),
    (7, 8, 1499.98, "processing", "2026-05-30", None),
    (8, 9,  229.98, "processing", "2026-06-10", None),
    (9,10,  449.99, "pending",    "2026-06-14", None),
])

con.executemany("INSERT INTO order_items VALUES (?,?,?,?,?)", [
    (1, 1, 1, 1, 1299.99),(2, 1, 2, 1, 29.99),
    (3, 2, 3, 1, 49.99),
    (4, 3, 4, 1, 449.99),(5, 3, 5, 1, 89.99),
    (6, 4, 5, 1, 89.99),
    (7, 5, 6, 1, 59.99),(8, 5, 8, 1, 199.99),
    (9, 6, 7, 1, 99.99),
    (10,7, 1, 1,1299.99),(11,7, 4, 1, 449.99),
    (12,8, 2, 1, 29.99),(13,8, 8, 1, 199.99),
    (14,9, 4, 1, 449.99),
])

con.executemany("INSERT INTO migrations VALUES (?,?,?)", [
    (1, "001_initial_schema",     "2022-03-15 09:00:00"),
    (2, "002_add_user_roles",     "2022-06-20 14:30:00"),
    (3, "003_add_order_items",    "2022-09-10 11:00:00"),
    (4, "004_add_product_status", "2023-01-05 10:00:00"),
    (5, "005_add_migrations_tbl", "2023-03-18 16:00:00"),
])

con.commit()

# Print summary
print("\nproduction.db created - real e-commerce database")
print("="*50)
for tbl in ["users","products","orders","order_items","migrations"]:
    n = con.execute(f"SELECT COUNT(*) FROM {tbl}").fetchone()[0]
    print(f"  {tbl:<16} {n} rows")

con.close()
print("\nDatabase setup complete.")
